import '../styles/globals.css'
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

import store from '../redux/store';
import {Provider} from "react-redux"


function MyApp({ Component, pageProps }) {
  return (

    <Provider store={store}>
      <Head>
          <title> Next Pizza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <Component {...pageProps} />

      <Footer />

    
    </Provider>
    ) 
}

export default MyApp
